### ISSUE TITLE
Bug Fix: Rouge useEffect() draining Infura requests

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#363]
Not sure where the problem lies but Infura requests are getting drained and this is likely a useEffect constantly polling data.

**Comment by StErMi** [comment]
We should press the migration to typescript, eth-hooks with typescript, and move out components in a package for better readability of the code because at the moment it's really difficult to understand where the problem is.

Also creating sub-components instead of having only one giant `app.jsx` can cause re-render problems. When a parent components re-render all the child components (and child-of-child components and so on) rerender and it can cause these kinds of issues.

I had only a little time to review the code but for example having `const purpose = useContractReader(readContracts, "YourContract", "purpose");` and `const setPurposeEvents = useEventListener(readContracts, "YourContract", "SetPurpose", localProvider, 1);` seems to be causing a lot of calls to `Infura`. I need to deep dive a lot more but it's not an easy task.

**Comment by azf20** [comment]
Let's make sure we fix this in the new stage branch (cc @ShravanSunder) rather than trying to fix or edit anything on Master. I am happy to pick this one up

**Comment by StErMi** [comment]
@azf20 I gave a fast overview of the `useContractReader` and I don't think that the code/logic on the `stage` branch has changed. I think that @ShravanSunder on the `eth-hooks` project (typescript branch) has just moved the same code to typescript and nothing else, right?

**Comment by azf20** [comment]
Proposed initial fix here https://github.com/austintgriffith/eth-hooks/issues/23

**Comment by ShravanSunder** [comment]
This was done in eth hooks already. @austintgriffith  let me know if you encounter it again and we can reopen it?

**Comment by codenamejason** [comment]
@ShravanSunder can this be closed?

**Comment by ShravanSunder** [comment]
> @ShravanSunder can this be closed?
as far as i know yes. thanks for checking in
