### ISSUE TITLE
Debug Contracts tab error bug

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#913]
Testing this on my local machine and noticed a couple things:

To reproduce:
1. run `yarn chain`
2. run `yarn start`
3. navigate to the Debug Contracts tab
4. It shows loading... as expected but why is there an address yet? This is causing some side effects to happen and cause an error (see screens).

Expected: The user should be able to navigate to this tab and have proper status and no errors whether contracts have been deployed or not.

Note: Not sure if this is new behavior (will have to check `master` branch behavior) and may have nothing to do with this PR 🫣

<img width="939" alt="Screen Shot 2022-10-13 at 12 26 19 PM" src="https://user-images.githubusercontent.com/9419140/195653045-099bf046-c2fa-4577-8fe2-1bc680438a95.png">

<img width="550" alt="Screen Shot 2022-10-13 at 12 26 32 PM" src="https://user-images.githubusercontent.com/9419140/195653253-172b82f1-b922-4648-8fac-945824fcbabd.png">

<img width="559" alt="Screen Shot 2022-10-13 at 12 26 07 PM" src="https://user-images.githubusercontent.com/9419140/195653280-1bcc955d-81f2-4c3b-806e-ba73c8868791.png">

_Originally posted by @codenamejason in https://github.com/scaffold-eth/scaffold-eth/pull/896#pullrequestreview-1141140649_

**Comment by technophile-04** [comment]
Hii @codenamejason, I tried reproducing this with fresh scaffold-eth install and it seem to work : 
![Screenshot 2022-10-14 at 2 37 50 PM](https://user-images.githubusercontent.com/80153681/195808973-3af2f822-1af1-48fd-bfcb-62f43a6b4fcd.jpg)

This behavior happens when : 
1. run `yarn chain`
2. run `yarn deploy` (deploys the contract and creates `hardhat_contracts.json` in `react-app/src/contracts`, adds deployed `contract address`,`abi`  in `hardhat_contracts.json`)
3. kill the local chain 
4. run `yarn chain` (This is the new chain and the previous deployed contract is not present on this chain)
5. run `yarn start` (It first creates `hardhat_contracts.json` if its not present, with an empty object,  in our case its already present and then spins up the react app)

Now since `hardhat_contracts.json` has `contract address` and everything init (but all this is not present in new local chain) that's why `Contract` component is displaying the address of the previous deployed contract but not loading the functions and all because its not present on actual current chain. hope it makes sense 😅

Possible Solution : 
There is this hooked used in `Contract` component `useContractExistsAtAddress` which checks if contract exists and displays the loading which you shared  with some additions informations if its not present, maybe we can use it
