### ISSUE TITLE
Yarn deploy is failing

### ISSUE THREAD

**Issue by Mattiatore** [scaffold-eth/scaffold-eth#927]
Hi everyone, I am just getting started with scaffold-eth but I have some problems with the installation, I am following the quickstart steps but my yarn deploy is failing:
<img width="724" alt="Screenshot 2022-12-01 at 21 12 13" src="https://user-images.githubusercontent.com/47110871/205150197-1e00f054-161e-4142-9b0c-46173db01dab.png">
Did anyone have a similar issue before?
Thanks!

**Comment by Mattiatore** [comment]
To clarify, both the others steps work fine and I can access the localhost

**Comment by emadkaramad** [comment]
I experienced a different error while deploying the contract. I tried running the command with `sudo` and it deployed successfully.

`sudo yarn deploy`

**Comment by InsideTheSim** [comment]
Wanted to chime in that this is happening for me as well. Running the command with `sudo` has no effect on my end. Still receive the `Error HH108: Cannot connect to the network localhost. Please make sure your node is running, and check your internet connection and networks config` error.

I'm able to get around it by running node v16 in this window (I'm using `n` to easily switch node versions) but having to juggle node versions is a pain because `start` doesn't work with n16 due to the `--openssl-legacy-provider` flag.

My current flow to get this working across 3 terminal windows:

window 1:
```
n 18 
yarn install
yarn chain
```

window 2:
```
n 18
yarn start
```

window 3:
```
n 16
yarn deploy
```

Would be great to be able to just set-and-forget node v18. Would love to hear if anyone is able to get the `deploy` command working on v18.

**Comment by jshcrm** [comment]
For me, the scripts in `packages/hardhat/packages.json` were creating a network named `hardhat`, but in `packages/hardhat/hardhat.config.js` the defaultNetwork variable was `localhost`. I changed `localhost` to `hardhat` in hardhat config and that seemed to work. I then got an error that `packages/hardhat/deployements` directory did not exist, so I created and I can now see my contract on the frontend.

**Comment by jshcrm** [comment]
Notice `-- network hardhat` throughout these scripts

![Screenshot from 2022-12-20 10-41-03](https://user-images.githubusercontent.com/6903193/208731389-7ec1afc3-d8a5-4bbe-9a42-659e6192177b.png)

But here `defaultNetwork` variable was `localhost` - I think it should be `hardhat`

![image](https://user-images.githubusercontent.com/6903193/208731592-e822263c-4e2d-431c-af87-8ed23f75b76f.png)

And then I created this `deployments` folder after the CLI yelled at me for not having it

![image](https://user-images.githubusercontent.com/6903193/208731753-6933e996-e867-483f-ab58-d42ccee3cf3c.png)

**Comment by jshcrm** [comment]
I still just see this on the frontend, though, so maybe more needs to be done

![image](https://user-images.githubusercontent.com/6903193/208732304-92b07565-97eb-4dba-b6d2-943127785cfa.png)

**Comment by jshcrm** [comment]
Actually, looking at `App.jsx`, the frontend doesn't appear to be built to display any custom contracts you write, so maybe thats doing exactly what it's supposed to

**Comment by vbop9834** [comment]
The fix for this is to change the address in hardhat.config.js for localhost to 127.0.0.1

See
https://github.com/scaffold-eth/scaffold-eth/pull/950/commits/bea2a492f5c4221cb2545b9907404a65d0f3459d
